### ISSUE TITLE
Your theme has been removed from www.themes.gohugo.io

### ISSUE THREAD

**Issue by digitalcraftsman** [AlexFinn/simple-a#7]
Hello @AlexFinn,

you might (not) have noticed that the demo of your theme at https://themes.gohugo.io/ hasn't been available for some time. The maintainers of the Hugo theme repository (I'm one of them) started a "spring cleaning", meaning that we start to sort out themes whose builds break. Currently, your theme fails in the process of generating such a demo.

Your theme has been suggested to be removed. You can find more information about the build errors in https://github.com/gohugoio/hugoThemes/pull/481). It would be great if you could fix the corresponding issues so we can add your theme again.

**Comment by AlexFinn** [comment]
Hallo @digitalcraftsman,

thanks. Will fix today.

**Comment by AlexFinn** [comment]
Fixed

**Comment by digitalcraftsman** [comment]
Great :+1: . I've added your theme again in https://github.com/gohugoio/hugoThemes/commit/f3778c839323cf88cc6298ae736f9112ec44029a.

**Comment by AlexFinn** [comment]
Thanks!
